# Copyright (c) 2023 Joseph Hale
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

settings:
  enabled: true
  debug: false
  language: en

example:
  message: "Hello from PapermcPluginTemplate!"
  max_players: 100
  allow_pvp: true
  blocked_worlds:
    - "world_nether"
    - "world_the_end"

